name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: terraform fmt check
        uses: hashicorp/setup-terraform@v2
        with: { terraform_version: 1.6.0 }
      - run: terraform fmt -recursive
      - run: terraform fmt -check

  terraform-plan:
    needs: terraform-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: 1.6.0 }
      - name: Configure AWS credentials from role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GITHUB_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - run: terraform init
      - run: terraform plan -out=tfplan

  terraform-apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with: { terraform_version: 1.6.0 }
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GITHUB_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - run: terraform init
      - run: terraform apply tfplan -auto-approve

